dataset_root: D:\Robot-Origami-Challenge\Competition_Paper_Reprocessed_Dataset
num_workers: 10
max_episodes: 10

spline:
  target: action_65d
  spline_scope: full_episode
  degree: 3
  epsilon: 0.0085 #0.00523
  error_metric: max_abs_joint # mae_65d # max_abs_joint # rmse_65d
  initial_internal_knots: 4
  max_internal_knots: 10000
  min_knot_spacing_frames: 1
  endpoint_weight: 1000.0

output:
  # Set this to null to write each spline next to its source arrays in the dataset.
  output_dir: E:/Robot-Origami-Challenge/dataset-processing/action_episode_spline_constructor/temp
  target_array_name: action_65d.npy
  state_array_name: state_65d.npy
  spline_npz_name: global_action_spline.npz
  spline_index_name: global_action_spline_index.parquet
  save_delta_from_initial_state: true
  delta_spline_npz_name: global_delta_action_from_initial_state_spline.npz
  delta_spline_index_name: global_delta_action_from_initial_state_spline_index.parquet
  run_summary_csv_name: global_action_spline_run_summary.csv
  run_summary_yaml_name: global_action_spline_run_summary.yaml
  overwrite: true
